server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /products {
        proxy_pass http://products-service:3001/products;
        proxy_set_header Host $host;
    }
    location /orders {
        proxy_pass http://orders-service:3002/orders;
        proxy_set_header Host $host;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}